require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/checklist_instances", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ChecklistInstance. As you add validations to ChecklistInstance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChecklistInstance.create! valid_attributes
      get checklist_instances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      checklist_instance = ChecklistInstance.create! valid_attributes
      get checklist_instance_url(checklist_instance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_checklist_instance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      checklist_instance = ChecklistInstance.create! valid_attributes
      get edit_checklist_instance_url(checklist_instance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChecklistInstance" do
        expect {
          post checklist_instances_url, params: { checklist_instance: valid_attributes }
        }.to change(ChecklistInstance, :count).by(1)
      end

      it "redirects to the created checklist_instance" do
        post checklist_instances_url, params: { checklist_instance: valid_attributes }
        expect(response).to redirect_to(checklist_instance_url(ChecklistInstance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChecklistInstance" do
        expect {
          post checklist_instances_url, params: { checklist_instance: invalid_attributes }
        }.to change(ChecklistInstance, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post checklist_instances_url, params: { checklist_instance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested checklist_instance" do
        checklist_instance = ChecklistInstance.create! valid_attributes
        patch checklist_instance_url(checklist_instance), params: { checklist_instance: new_attributes }
        checklist_instance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the checklist_instance" do
        checklist_instance = ChecklistInstance.create! valid_attributes
        patch checklist_instance_url(checklist_instance), params: { checklist_instance: new_attributes }
        checklist_instance.reload
        expect(response).to redirect_to(checklist_instance_url(checklist_instance))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        checklist_instance = ChecklistInstance.create! valid_attributes
        patch checklist_instance_url(checklist_instance), params: { checklist_instance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested checklist_instance" do
      checklist_instance = ChecklistInstance.create! valid_attributes
      expect {
        delete checklist_instance_url(checklist_instance)
      }.to change(ChecklistInstance, :count).by(-1)
    end

    it "redirects to the checklist_instances list" do
      checklist_instance = ChecklistInstance.create! valid_attributes
      delete checklist_instance_url(checklist_instance)
      expect(response).to redirect_to(checklist_instances_url)
    end
  end
end
